# Generated by Django 3.1.7 on 2021-02-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
    ]
